"""add photo filename

Revision ID: 06efe96365d4
Revises: 1ce3e2d3eb6d
Create Date: 2023-05-10 12:00:02.603665

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06efe96365d4'
down_revision = '1ce3e2d3eb6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('facility_photo', sa.Column('filename', sa.String()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('facility_photo', 'filename')
    # ### end Alembic commands ###
