name: deploy

on:
  push:
    tags:
      - v**

jobs:
  deploy:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: docker://postgres
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user123
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: sportsmap_test
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: "3.11"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint
        run: |
          pylama .
      - name: Test
        run: |
          API_PORT="8080" \
          API_TEST_DB_URL="postgresql+asyncpg://user123:123@localhost:5432/sportsmap_test" \
          API_DB_URL="postgresql+asyncpg://user123:123@localhost:5432/sportsmap_test" \
          API_SUPERUSER_EMAIL="krendeleno@gmail.com" \
          API_SUPERUSER_PASSWORD="123" \
          pytest .
      - name: get-docker-version
        run: sh ./scripts/get-version.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          IMAGE_NAME: sportsmap-backend-new
      - name: deploy-docker-backend
        run: sh ./scripts/deploy.sh
        env:
          OAUTH: ${{ secrets.OAUTH }}
          REGISTRY_ID: ${{ secrets.REGISTRY_ID }}
          VERSION: ${{ env.NEW_VERSION }}
          API_PORT: 8080
